import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    {
      type: 'category',
      label: 'Onboarding',
      link: {
        type: 'generated-index',
        title: 'Onboarding',
        description: 'Get started quickly with BBS.',
      },
      items: [{type: 'autogenerated', dirName: 'onboarding'}],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Task-focused walkthroughs and tutorials.',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture',
        description: 'System design and architecture decision records.',
      },
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      link: {
        type: 'generated-index',
        title: 'Deployment',
        description: 'Packaging and deployment notes.',
      },
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        title: 'Reference',
        description: 'Contracts, APIs, and protocols.',
      },
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Releases',
      link: {
        type: 'generated-index',
        title: 'Releases',
        description: 'Roadmap, versioning, and release planning artifacts.',
      },
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
    {
      type: 'category',
      label: 'Local Working Notes',
      link: {
        type: 'generated-index',
        title: 'Local Working Notes',
        description: 'Internal local notes and working documents.',
      },
      items: [{type: 'autogenerated', dirName: 'local'}],
    },
  ],
};

export default sidebars;
