FROM golang:1.22-alpine AS build
WORKDIR /src
ARG BUILD_VERSION=unreleased

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w -X main.buildVersion=${BUILD_VERSION}" -o /out/bbs-server ./cmd/bbs-server

FROM alpine:3.20
WORKDIR /app/cmd/bbs-server

COPY --from=build /out/bbs-server ./bbs-server
COPY cmd/bbs-server/templates ./templates

EXPOSE 8080 3000
ENTRYPOINT ["./bbs-server"]
